config/routes.rb
Rails.application.routes.draw do

  resources :recipes

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'recipes#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  belongs_to :ingredient

  # validates :quantity, :numericality => { :greater_than => 0 }
  
  def servingsize(number)
    if number
      newnumber = number.to_i / self.ingredient.recipes.first.serving
      wholefraction = (self.quantity * newnumber).to_fraction
    else
      wholefraction = self.quantity.to_fraction
    end
    if wholefraction[1] <= 1
      return wholefraction[0]
    end
    fraction = Rational(wholefraction[0], wholefraction[1])
    numeric_to_mixed_number(fraction)
  end

  def numeric_to_mixed_number(amount)
    amount_as_integer = amount.to_i
    if (amount_as_integer != amount.to_f) && (amount_as_integer > 0)
      fraction = amount - amount_as_integer
      "#{amount_as_integer} #{fraction}"
    else
      amount.to_s
    end
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  has_many :joinirtables
  has_many :recipes, through: :joinirtables

  has_many :amounts, dependent: :destroy
  accepts_nested_attributes_for :amounts, :reject_if => lambda { |a| a[:quantity].blank? }, :allow_destroy => true, update_only: true
end

app/models/joinirtable.rb
class Joinirtable < ActiveRecord::Base

  belongs_to :recipe
  belongs_to :ingredient

end

app/models/recipe.rb
require "open-uri"

class Recipe < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :photo, :styles => {  small: "150x150>", med: "350x350>", large: "500x500>" }

  has_many :steps, dependent: :destroy

  has_many :joinirtables
  has_many :ingredients, through: :joinirtables

  accepts_nested_attributes_for :ingredients, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true, update_only: true
  accepts_nested_attributes_for :steps, :reject_if => lambda { |a| a[:instruction].blank? }, :allow_destroy => true, update_only: true

  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => %w(image/jpeg image/jpg image/png)
  validates :title,
    presence: true

  def current_serving(serving)
    if serving
      return serving
    else 
      self.serving
    end
  end

  def picture_from_url(url)
    self.photo = URI.parse(url)
  end

  def self.search(search)
    if search
      where('title LIKE :search' , {:search => "%#{search}%"})
    else
      find(:all)
    end
  end

end

app/models/scraper.rb
require 'nokogiri'
require 'open-uri'

class Scraper

  attr_reader :url, :data

  def initialize(url)
    @url = url
  end

  def get_properties(property)
    data.search(property).map do 
      |e| e.inner_text
    end
  end

  def get_img
    src = 'http://www.epicurious.com' + data.at('.photo')['src'].to_s
  end

  def data
    @data ||= Nokogiri::HTML(open(url))
  end

end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :recipe

  validates :instruction,
  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :recipes
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_filter :restrict_access

  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    1.times do
      ingredient = @recipe.ingredients.build
      1.times { ingredient.amounts.build }
    end
    1.times { @recipe.steps.build }
  end

  def edit
    @file_found = true
    @recipe = Recipe.find(params[:id])
    if @recipe.photo == nil
      @file_found = true
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update_attributes(update_recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def create
    if params[:url].blank?
      redirect_to new_recipe_path
    elsif params[:url]
      scraper = Scraper.new(params[:url])
      title = scraper.get_properties('#headline > h1:first-child')[0]
      if scraper.get_properties('.summary_data > span')[0] == nil
        serving = 1
      else
        serving = scraper.get_properties('.summary_data > span')[0].scan(/\d+/).first.to_r.to_f 
      end
      photourl = scraper.get_img
      @recipe = Recipe.new(title: title, serving: serving)
      @recipe.picture_from_url(photourl)
      # @recipe.photo = photourl

      ingredients = scraper.get_properties('.ingredient')
      for ingredient in ingredients do
        amount = ingredient.split(/[a-zA-Z]/)[0]
        amounts = amount.split(" ")
        amount_integer = amounts[1].to_r.to_f + amounts[0].to_r.to_f
        ingredient.slice! amount
        @recipe.ingredients << Ingredient.new(name: ingredient)
        if amount_integer > 0
          @recipe.ingredients.last.amounts << Amount.new(quantity: amount_integer)
        end
      end

      steps = scraper.get_properties('#preparation > p')
      for step in steps do
        @recipe.steps << Step.new(instruction: step)
      end
      @recipe.user_id = current_user.id
      @recipe.save
      redirect_to recipe_path(@recipe.id)
    else
      @recipe = Recipe.new(recipe_params)
      if @recipe.save
        redirect_to recipes_path
      else
        render :new
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end

  protected

  def recipe_params
    params.require(:recipe).permit(
      :title, steps_attributes: [:instruction], ingredients_attributes: [ :name, amounts_attributes: [:quantity]]
    )
  end

  def update_recipe_params
    params.require(:recipe).permit(
      :title, :photo, :serving
    )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to recipes_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to recipes_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  before_filter :restrict_access, :only => [:show]

  def index
  end

  def show
    @user = User.find(current_user.id)
    if params[:search]
      @recipes = @user.recipes.search(params[:search])
    else 
      @recipes = @user.recipes.all
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

end

app/helpers/link_to_function_helper.rb
module LinkToFunctionHelper
  def link_to_function(name, *args, &block)
     html_options = args.extract_options!.symbolize_keys

     function = block_given? ? update_page(&block) : args[0] || ''
     onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
     href = html_options[:href] || '#'

     content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<!-- <nav class="clearfix">  
<ul class="clearfix"> 



</ul>  
<a id="pull">Menu</a>  
</nav>  

<% if current_user %>
  <%= current_user.firstname %> <%= current_user.lastname %>
<% else %>
  <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
<% end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lobster+Two:700,400' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
  <%= render 'layouts/header' %>
  <%= yield %>

</body>
</html>

app/views/recipes/_amount_fields.html.erb
<div class='fields'>
  Amount: <%= f.number_field :quantity %>
  <%= link_to_remove_fields "remove", f %>
</div>
<br>

app/views/recipes/_form.html.erb
<%= form_for @recipe, :html => { :multipart => true } do |f| %>
  <div class="inline">
    Title:<br>
    <%= f.text_field :title %>
  </div>
  <div class="inline">
    Serving:<br>
    <%= f.number_field :serving %>
  </div>
  <div class="inline">
    <%= link_to "Back to your recipes", user_path(current_user.id) %>
  </div>
  <br>
  <hr>

  <div class='wrap'>
    <h2> Ingredients </h2>
      Photo:<br>
      <% if @file_found == true %>
        <%= image_tag @recipe.photo.url(:med)%> <br>
        Replace Image: <%= f.file_field :photo %>
      <% else %>
        <%= f.file_field :photo %>
      <% end %>

    <br>
    <hr>

    <%= f.fields_for :ingredients do |builder| %>
      <%= render "ingredient_fields", :f => builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Ingredient", f, :ingredients %></p>
  </div>

  <div class='wrap'>
    <h2> Instructions </h2>
    <%= f.fields_for :steps do |builder| %>
      <%= render "step_fields", :f => builder %>
    <% end %>
    <p><%= link_to_add_fields "Add Step", f, :steps %></p>

    <%= f.submit :Submit %> 
  </div>

<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="fields">  
  <div>
    Ingredient:<br>
    <%= f.text_field :name %>
    <%= link_to_remove_fields "remove", f %>
  </div>

  <%= f.fields_for :amounts do |builder| %>
    <%= render "amount_fields", :f => builder %>
  <% end %>
  <p><%= link_to_add_fields "Add Amount", f, :amounts %></p>
</div>

app/views/recipes/_step_fields.html.erb
<div class="fields">
  Step:<br>
  <%= f.text_area :instruction, :rows => 4, :id => "text-area" %>
  <%= link_to_remove_fields "remove", f %>
</div>
<br>

app/views/recipes/edit.html.erb
<%= render 'form' %>

app/views/recipes/index.html.erb
<section class='index'>

  <img src="<%= asset_path( 'main-logo.jpg' ) %>"/>
  <div class='index-links'>
    <%= form_for recipes_path, :html => { :id => 'form' }, :method => 'post' do %>
        <br>
        <p><%= text_field_tag :url, nil, placeholder: "Paste recipe URL here!" %></p>
    <% end %> 
    <div class='lower-links'>
      <p><a href="javascript:{}" onclick="document.getElementById('form').submit();">Submit recipe!</a></p>
      <p><%= link_to "Make your own recipe!", new_recipe_path %></p>
      <p><%= link_to "Your recipes!", user_path(current_user.id) %></p>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<%= link_to "Back to all recipes", recipes_path %>

<h2>Submit a recipe!</h2>
<%= render 'form' %>

app/views/recipes/show.html.erb
<div class='topbar'></div>
<h2 class='title'><%= @recipe.title %></h2>


<section class='wrap'>
  <%= image_tag @recipe.photo.url(:med), :class => "image" %>

    <h3>Instructions</h3>
    <ol>
    <% @recipe.steps.each do |step| %>
      <li><%= step.instruction %></li>
    <%end%>

    <hr>
    <%= link_to "Delete Recipe", recipe_path(@recipe), method: :delete, confirm: "You sure?" %> | <%= link_to "Back to all recipes", user_path(current_user.id) %> | <%= link_to "edit", edit_recipe_path(@recipe) %>
    </ol>
</section>

<section class='wrap'>

  <h3 class='inline'>Ingredients</h3> 
  <div class='inline'>
  <%= form_for recipes_path, :html => { :id => 'form' }, :method => 'get' do %>
    <ul class='inline'> <em>Serving|Yield:</em> <%= number_field_tag :serving, @recipe.current_serving(params[:serving]), in: 1...101%></ul>
  <% end %> 
  </div>
  <hr>
  <% @recipe.ingredients.each do |ingredient| %>
    <ul> 
      <% for amount in ingredient.amounts %>
        <%= amount.servingsize(params[:serving]) %>
      <% end %>
      <%= ingredient.name %>
    </ul>
  <%end%>

</section>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<section class='wrapper'>

  <div class='devide'>
    <h1> Mise En App! </h1>
    <hr>
    <h2>Sign Up</h2>
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div>
          <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label "email" %><br>
        <%= f.text_field "email" %>
      </div>
      <div>
        <%= f.label "firstname", "First Name" %><br>
        <%= f.text_field "firstname" %>
      </div>
      <div>
        <%= f.label "lastname", "Last Name" %><br>
        <%= f.text_field "lastname" %>
      </div>
      <div>
        <%= f.label "password" %><br>
        <%= f.password_field "password" %>
      </div>
      <div>
        <%= f.label "password_confirmation" %><br>
        <%= f.password_field "password_confirmation" %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>
    <%= link_to "Log In", new_session_path %>
  </div>

  <div class='devide'>
    <h2>Example!</h2>
    <div class='inside'>
      <div class='examples'>
        <p> Step 1: Find the recipe you want at www.epicurious.com </p>
        <img src="<%= asset_path( 'rsz_example1.png' ) %>"/>
      </div>
      <div class='examples'>
        <p> Step 3: Save the recipe and edit if you want! </p>
        <img src="<%= asset_path( 'rsz_example3.png' ) %>"/>
      </div>
      <div class='examples'>
        <p> Step 2: Copy the recipe URL and paste it into Mise En Ap! </p>
        <img src="<%= asset_path( 'rsz_example2.png' ) %>"/>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class='top-user'>
  <!-- <h1 class='app-title'>Mise En App!</h1> -->
  <img src="<%= asset_path( 'main-logo.jpg' ) %>" class='app-title' />
  <%= form_for recipes_path, :html => { :id => 'form', :class=> 'inline searchform' }, :method => 'get' do %>
    <div class='search'> <%= text_field_tag :search, params[:search] %>
      <div class='submit'><%= image_submit_tag("search.png", :name => nil, :class => 'submit') %></div>
    </div>
  <% end %> 
  <br>
  <div class='navbar'>
    <%= link_to( "Mise En App!", user_path(@current_user), :class => 'taskbar')%> <%= link_to( "Submit a recipe!", recipes_path, :class => 'taskbar' )%> <%= link_to( "Log out", session_path("current"), method: :delete, :class => 'taskbar' )%> 
  </div>
</section>

<section class='container'>
  <% @recipes.each do |recipe| %>
    <div class='recipe-preview'>
      <%= link_to( image_tag(recipe.photo.url(:large), :class => 'image-preview'), recipe_path(recipe)) %>
      <h2 class='title preview'><%= link_to recipe.title, recipe_path(recipe) %></h2>
      <ul> <em> Intended Serving|Yield: </em> <%=recipe.serving %></ul>
    </div>
  <% end %>
</section>